### ISSUE TITLE
Prawn::Errors::CannotFit in table when using custom font

### ISSUE THREAD

**Issue by tandibar** [jessedoyle/prawn-icon#21]
I am using a special font like this:

    font_families.update(
      "Monda" => {
        normal: File.join(Rails.root, "app/assets/fonts/monda/Monda-Regular.ttf"),
        bold: File.join(Rails.root, "app/assets/fonts/monda/Monda-Bold.ttf")
      }
    )
    font "Monda"

if i run your simple example after that 

    data = [
      [table_icon('fa-birthday-cake'), 'Cake'],
      ['is', 'Great!']
    ]
    table(data)

it crashes with `Prawn::Errors::CannotFit` exception. Any idea?

**Comment by jessedoyle** [comment]
@tandibar - Thanks for filing an issue!

Any chance you can provide me a link to the `.ttf` files that you're using?

I've noticed this issue before, and I believe the issue lies in the code for `Prawn::Table` (see my comment in #6). With the proper font files, I should be able to replicate the issue and further investigate the issue.

**Comment by jessedoyle** [comment]
Oops, I linked to the wrong Github issue in my last comment. I meant #7.

**Comment by jessedoyle** [comment]
I found the necessary font files on Google fonts. Here's some initial observations:

- The `Prawn::Errors::CannotFit` exception is thrown because there is not enough width in the table's `TextBox` to render the icon. This is [tested and appropriate behaviour](https://github.com/prawnpdf/prawn/blob/03475bb3a39baa1c8bb60d9f215e1b89615f0d45/spec/line_wrap_spec.rb#L33) in Prawn.
- I _believe_ that somewhere in `Prawn::Table` the minimum cell width is not being calculated properly, but I'm not quite sure yet.

For the time being, you can simply force the table cell to have a certain width when dealing with custom fonts:

```ruby
  font 'Monda'

  data = [
    [table_icon('fa-birthday-cake', width: 24), 'Cake'],
    ['is', 'Great!']
  ]

  table(data)
```

The real question is:

Why is `Prawn::Table` not determining an appropriate minimum width for the cell that includes the icon? Perhaps the font change is not being handled properly - I'll need to dig deeper.

**Comment by jessedoyle** [comment]
I can confirm that this is caused by a defect in the `Prawn::Table` codebase.

Please see [Prawn::Table #42](https://github.com/prawnpdf/prawn-table/issues/42). `Prawn::Table` appears to not consider the cell's specified font went calculating the minimum width requirements for a table cell.

Furthermore, [this code](https://github.com/prawnpdf/prawn-table/blob/master/lib/prawn/table/cell/text.rb#L136-L150) reveals that `Prawn::Table` naively uses the `M` character as the widest individual character in a font. Clearly this behaviour is incompatible with icon fonts.

@tandibar - I'm going to keep this issue open for a few days as reminder to myself, but there is not very much that can be done for this issue from `Prawn::Icon`'s perspective (other than specifying the cell's width).

**Comment by tandibar** [comment]
Hi, thx for taking care so your quickly. I just tried with manually setting width and it works. I need to set at least 19 as width. But there is much white space in the cells.
![bildschirmfoto 2015-11-11 um 19 37 05](https://cloud.githubusercontent.com/assets/411/11099434/a5b65bbe-88ab-11e5-8ef7-5ef60ed990a1.png)

I will see what `Prawn::Table` does to take care of this. For me it's totally okay to close this issue.

**Comment by jessedoyle** [comment]
Perfect thanks!

**Comment by jessedoyle** [comment]
Also note that the `valign` and `align` settings may be useful for moving the icons around in the cell:

```ruby
  data = [
    [table_icon('fa-birthday-cake', width: 24, valign: :center, align: :center), 'Cake'],
    ['is', 'Great!']
  ]

  table(data)
```
