### ISSUE TITLE
using with prawn-rails

### ISSUE THREAD

**Issue by prees1** [jessedoyle/prawn-icon#31]
Do you know if prawn-icon works with [this project](https://github.com/cortiz/prawn-rails)?

It is complaining with: `undefined method 'icon' for #<PrawnRails::Document:0x007fc353dc23c8> (NoMethodError)`

Wondering if there is some other way I should be requiring it? I realize this isn't necessarily an issue that can be solved here. Just looking for help and wondering if its possible. Thanks!

**Comment by jessedoyle** [comment]
Hi @prees1 - I think I've got it figured out.

It looks like `PrawnRails` inherits from important `Prawn` classes. Because of this, the initialization `prawn-icon` performs [here](https://github.com/jessedoyle/prawn-icon/blob/master/lib/prawn/icon.rb#L14) is lost.

If you add this line to `config/initializers/prawn_rails.rb`, you should be able to initialize `prawn-icon` with `PrawnRails`:

```ruby
PrawnRails::Document.extensions << Prawn::Icon::Interface
PrawnRails.config do |config|
  # your configuration here
end
```

Please give that a shot and let me know if it works for you!

**Comment by prees1** [comment]
That was it, works like a charm! Thanks @jessedoyle
