### ISSUE TITLE
Can I add a fontawesome icon not currently mapped? 

### ISSUE THREAD

**Issue by jcrone** [jessedoyle/prawn-icon#56]
I couldn't figure it out, so I thought maybe I had to fork , to add a new character 
diamond: "◆"
in the fas.yml file but it didnt work for me also swtiched out the line
fa-diamond: fas-gem with fa-diamond: fas-diamond in the shim.yml file

Any suggestions?

**Comment by jcrone** [comment]
I figured it out, I had to add the font to your ttf file. Just took me a while to figure how to do that

**Comment by jessedoyle** [comment]
Hi there @jcrone - thanks for using Prawn::Icon!

This gem currently uses FontAwesome 5.15.1 instead of 6.x. It looks like back in the 5.x series, `fas-diamond` [was a pro-level icon](https://fontawesome.com/v5/icons/diamond?s=solid), which [aren't supported out of the box](https://github.com/jessedoyle/prawn-icon/issues/54#issuecomment-1020408730).

With that being said it looks like it's no longer a pro-level icon in version 6, so maybe it's time to update!

PRs would be welcome to upgrade to FontAwesome v6, thanks!
