### ISSUE TITLE
table_icon doesn't exist

### ISSUE THREAD

**Issue by gshiftlabs-mwinger** [jessedoyle/prawn-icon#8]
I took your README example:

require 'prawn'
require 'prawn/icon'
require 'prawn/table'

Prawn::Document.generate('table_icons.pdf') do |pdf|

  data = [
    # Explicit brackets must be used here
    [pdf.table_icon('fa-birthday-cake'), 'Cake'],
    ['is', 'Great!']
  ]

  pdf.table(data) # => (2 x 2 table)
end

and tried to run that - pdf.table_icon doesn't exist.

**Comment by gshiftlabs-mwinger** [comment]
nevermind - the repo appears to have it, but the actual gem does not yet.

**Comment by jessedoyle** [comment]
@gshiftlabs-mwinger - The `table_icon` method was added in v0.6.2. This version is currently the latest version on RubyGems.

**Comment by gshiftlabs-mwinger** [comment]
strange.. is it possible that because I had prawn 1.2.1, it would have requested a lower version from RubyGems? For anyone else reading - this looks like it was entirely my own fault/issue.

Right now I've got my Gemfile pointed at the git repo, not sure how good of an idea that is. I'll look at forcing a version for the gem from RubyGems soon.

Thanks for the reply :)

**Comment by jessedoyle** [comment]
Prawn/Icon 0.6.2 has a runtime dependency of Prawn 1.3.0 or higher. It's likely that bundler or a similar program installed a lower version of Prawn/Icon because of the lack of this dependency.

There should be no problems actually running the latest code with many older version of Prawn. I'm going to think a bit on it, but I'll likely release a newer version with a relaxed dependency on the Prawn version.

**Comment by jessedoyle** [comment]
@gshiftlabs-mwinger FYI: I've pushed version 0.6.3 to RubyGems. This update relaxes the runtime Prawn dependency to prawn >= 1.1.0.
